config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  Rails.application.routes.draw do

    resources :restaurants , only: [:index, :show, :new, :create] do



    resources :reviews, only: [:new, :create]

    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
 validates :name, :address, :category, presence: true
 validates :category, inclusion: { in: %w(chinese italian japanese french belgian)}
has_many :reviews, dependent: :destroy
end
   

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, numericality: { only_integer: true }
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.save
  end

  private
  
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(review_params)
    @review.save
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="page">
<h1>All Restaurants</h1>

<%= link_to 'Add New Restaurant', new_restaurant_path, class: 'button-link' %>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>
</div>

app/views/restaurants/new.html.erb
<div class="page">

<h1>New Restaurant </h1>

<%= simple_form_for (@restaurant) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :category %>
  <%= f.select :category, options_for_select(['chinese', 'italian', 'japanese', 'french', 'belgian']) %>

  <%= f.submit 'Create Restuarant', class: "submit-button"%>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="page">

<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p>Category: <%= @restaurant.category %></p>

<h2>Reviews</h2>
<%= link_to 'Add Review', new_restaurant_review_path(@restaurant), class: 'button-link' %>

<ul>
  <% @reviews.each do |review| %>
    <li>
      <strong>Rating:</strong> <%= review.rating %><br>
      <strong>Content:</strong> <%= review.content %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back to All Restaurants', restaurants_path, class: 'button-link' %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="page">

<h1>New Review for <%= @restaurant.name %></h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating %>

    <%= f.input :content %>

    <%= f.submit%>
<% end %>
</div>